### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by MathiasCiarlo** [gardir/Devilry_sort#1]
Traceback (most recent call last):
  File "/Devilry_sort/sort_deliveries.py", line 270, in <module>
    sorter.run()
  File "/home/Devilry_sort/sort_deliveries.py", line 128, in run
    self.null_file.close()
AttributeError: Devilry_Sort instance has no attribute 'null_file'

**Comment by gardir** [comment]
Fixed bug, was a not completely done refactoring of variable. See last commit :)
