### ISSUE TITLE
No compatibility for cmd on Windows

### ISSUE THREAD

**Issue by silmer** [gardir/Devilry_sort#5]
Can't unzip files when running the script in Windows cmd.

> ==== Automatisk rettescript for INF1000 ====
> 
> ---> Pakker ut alle filer...
> Traceback (most recent call last):
>   File "retteskript.py", line 81, in <module>
>     unzip(filename)
>   File "retteskript.py", line 14, in unzip
>     returnvalue = call(["unzip", "-qo", filename])
>   File "C:\python27\lib\subprocess.py", line 522, in call
>     return Popen(_popenargs, *_kwargs).wait()
>   File "C:\python27\lib\subprocess.py", line 710, in **init**
>     errread, errwrite)
>   File "C:\python27\lib\subprocess.py", line 958, in _execute_child
>     startupinfo)
> WindowsError: [Error 2] The system cannot find the file specified

**Comment by KGHustad** [comment]
Windows compatibility was improved (i.e. it still doesn't work, but it's closer to working than before) with 199ea11, but no changes were made to the unzipping part. 

Python does have a library for handling zip files (https://docs.python.org/2/library/zipfile.html), so it should be possible to use this instead of using `unzip`
